- repo/packages/cray-mpich-binary/package.py
`cray-mpich-binary/package.py` now uses patchelf to fix a missing link for libstdc++,
which caused builds to fail with the C MPI compiler wrapper.
Fixes #9
> Cray mpich/libstc++

- readme.md
- sstool/main.py
- templates/Makefile.packages
- templates/packages.spack.yaml
- test/recipes/base-amdgpu/packages.yaml
- test/recipes/base-nvgpu/packages.yaml
- test/recipes/cache/packages.yaml
- test/recipes/host-recipe/packages.yaml
- test/recipes/unique-bootstrap/packages.yaml
Extend the `packages.yaml` recipes to accept a list of compilers instead of a single compiler.
This makes it possible to provide a fallback gcc for packages that can't be built by the primary compiler.
**Before**:
```yaml
compiler:
toolchain: llvm
spec: nvhpc
```
**After**:
```yaml
compiler:
- toolchain: llvm
spec: nvhpc
- toolchain: gcc
spec: gcc@11.3
```
> support multiple compilers per environment

- sstool/main.py
- templates/Makefile.packages
- templates/packages.spack.yaml
Add support for specifying system packages (e.g. `perl`, `git` and `ncurses`) that are
for an envrionment.
- each environment provides its own list
- the packages are marked as `--no-build`, so that the concretiser is forced to use them.
> optional per-environment system packages

- stackinator/builder.py
Fixes intermittent configuration errors when copying the contents of
a `.git` path inside a recipe (if present) to the meta data in the image.
> don't copy .git path to recipe meta to avoid configuration errors

- .github/workflows/lint.yaml
- .isort.cfg
- bin/stack-config
- pyproject.toml
- stackinator/__init__.py
- stackinator/builder.py
- stackinator/main.py
- stackinator/recipe.py
- stackinator/repo/packages/cray-mpich/package.py
- stackinator/schema.py
- test_stackinator.py
- unittests/test_schema.py
This PR
* Formats the codebase with `black`
* Formats the codebase with `isort`
* Adds `isort.cfg`
* Adds `lint.yaml` action to enforce `black` and `isort`
A separate PR will follow with `flake8` and `mypy`; I didn't want to add those changes here so that they can be properly reviewed. This PR consists only in the result of `black .` and `sort .`.
In the separate PR, I'll also add a `.git-blame-ignore-revs` with the appropriate commit hash so that the changes in this PR will be ignored by `git blame`.
> Format with black and isort

- README.md
- stackinator/builder.py
- unittests/recipes/with-repo/compilers.yaml
- unittests/recipes/with-repo/config.yaml
- unittests/recipes/with-repo/environments.yaml
- unittests/recipes/with-repo/repo/packages/dummy/package.py
- unittests/test_schema.py
This PR adds support for user-provided packages, so that custom packages can be provided when building the stack. These packages can be new ones, or versions taking precedence over the ones in upstream Spack (as for the `cray-mpich` package).
You can find example recipes here: https://github.com/RMeli/spack-stack-alps/tree/main/hohgant/tests
The recipe structure is the following:
```bash
.
├── compilers.yaml
├── config.yaml
├── environments.yaml
├── mirrors.yaml
└── repo
├── packages
│   └── elpa
│       └── package.py
└── repo.yaml
```
Besides the usual suspects, the user can now provide a `repo` directory defining a [Spack repository](https://spack.readthedocs.io/en/latest/repositories.html). The `repo.yaml` file is optional and will overwrite the `stackinator/repo/repo.yaml` one.
--- …
> Allow user-provided packages

- stackinator/templates/Make.user
* Set `LC_ALL` to `en_US.UTF-8`
> Fix python decoding errors when reading files

- stackinator/etc/bwrap-mutable-root.sh
If there is a broken symlink in root, the bwrap wrapper will fail.
Fix this by mounting everything _except_ invalid symlinks.
> Fix bwrap mounting for broken links

- stackinator/templates/Makefile.compilers
- stackinator/templates/Makefile.environments
Sometime around v0.20, Spack started colorizing the output of `spack -e ... find --format '/{hash}'`, which we were piping straight into another Spack command. Hilarity ensues.
> Fix builds with v0.20 of spack

- stackinator/recipe.py
- stackinator/templates/Makefile.compilers
- stackinator/templates/Makefile.environments
Some large packages take an extreme length of time to push to build caches.
For example, `nvhpc` and `cuda` which are 5-15 GB in size, can take 10 minutes.
These are binary pacakges, that do not need to be built, so subsequent time savings
might not be worth the time added by pushing to a cache the first time that they are
installed.
This PR introduces a change that selectively filters `nvhpc` and `cuda` when enumerating
the packages to push to a cache.
The feature could be later extended to give users more control over which packages to skip.
Fixes #95
> Don't push large binary images to build caches

- docs/recipes.md
- stackinator/builder.py
- stackinator/schema/config.json
- unittests/recipes/host-recipe/config.yaml
- unittests/test_schema.py
- unittests/yaml/config.full.yaml
* add `description` field to `config.yaml`
* add more information about the environment, views, modules, etc to `meta/env.json`. See below
```json
{
"description": "An example gcc configuration for CPU-only development",
"modules": {
"root": "/user-environment/modules"
},
"name": "host-example",
"views": {
"default": {
"activate": "/user-environment/env/default/activate.sh",
"description": "",
"root": "/user-environment/env/default"
},
"no-python": {
"activate": "/user-environment/env/no-python/activate.sh",
"description": "",
"root": "/user-environment/env/no-python"
},
"roots": {
"activate": "/user-environment/env/roots/activate.sh",
"description": "",
"root": "/user-environment/env/roots"
},
"run": {
"activate": "/user-environment/env/run/activate.sh",
"description": "",
"root": …
```
> improve env.json meta data; add description to config

- stackinator/cache.py
When using a `cache-config.yaml` with an invalid entry for `key`, stackinator printed the following message:
```
The build cache key '/scratch/e1000/simonpi/uenv-cache' does not exist        
```
Seems to be a copy/paste error reusing the previous block for `path`
> fix build cache error message

- docs/configuring.md
Add `--develop` option (introduced in #122) to the documentation. Close #137.
> Document --develop option

- stackinator/main.py
When trying to install matplotlib, `font-util` installation failed:
```
/usr/bin/fc-cache /user-environment/linux-sles15-zen2/gcc-11.4.0/font-util-1.4.0-b6tqwcjmvtuzuybtahwl7oa5gpxqvctm/share/fonts/X11/100dpi
/user-environment/linux-sles15-zen2/gcc-11.4.0/font-util-1.4.0-b6tqwcjmvtuzuybtahwl7oa5gpxqvctm/share/fonts/X11/100dpi: failed to write cache
make[4]: *** [Makefile:890: install-data-hook] Error 1
make[4]: Leaving directory '/tmp/simonpi/spack-stage/spack-stage-font-util-1.4.0-b6tqwcjmvtuzuybtahwl7oa5gpxqvctm/spack-src/font-adobe-100dpi/font-adobe-100dpi-1.0.3'
make[3]: *** [Makefile:778: install-data-am] Error 2
make[3]: Leaving directory '/tmp/simonpi/spack-stage/spack-stage-font-util-1.4.0-b6tqwcjmvtuzuybtahwl7oa5gpxqvctm/spack-src/font-adobe-100dpi/font-adobe-100dpi-1.0.3'
```
In …
> set $HOME to ~

- stackinator/templates/Makefile.generate-config
Besides `builder.py` there were also files copied using `cp` to `/store`. Replace it by `install -m 644` to make sure the created image is world readable.
> use `install` instead of `cp` in makefile

- stackinator/schema.py
- stackinator/schema/environments.json
- unittests/test_schema.py
- unittests/yaml/environments.full.yaml
This PR:
- extends tests with a basic test-case with an environment where `mpi:gpu` field is not specified
- fix schema to have a default for the `mpi:gpu` field (default = `null`)
- fix validator to deal with non-existing sections
About this latter point, since I don't have any experience with this library, I'd like to ask you to double check (see comment in the code) if it is the correct reason/solution.
According to the documentation the `mpi:gpu` field is optional, but the schema and validator were not supporting that.
https://github.com/eth-cscs/stackinator/blob/e8219f5168eccd455ab0b6c46ad6c48f9657dec8/docs/recipes.md?plain=1#L141-L147
https://github.com/eth-cscs/stackinator/blob/e8219f5168eccd455ab0b6c46ad6c48f9657dec8/docs/recipes.md?plain=1#L149-L161
> Make `environment:mpi:gpu` optional

- docs/configuring.md
- stackinator/templates/Makefile.environments
`spack env activate` has changed `--with-view` flag, it requires an argument in latest develop:
```
usage: spack env activate [-hp] [--sh | --csh | --fish | --bat | --pwsh] [--with-view name | --without-view] [--temp] [-d DIR]
[env]
positional arguments:
env                   name of environment to activate
options:
...
--with-view name, -v name
set runtime environment variables for specific view
...
````
> fix --with-view argument in develop

- docs/configuring.md
- stackinator/builder.py
- stackinator/main.py
- stackinator/recipe.py
- stackinator/templates/Makefile
- stackinator/templates/Makefile.compilers
- stackinator/templates/Makefile.environments
* fix `spack env --with-view default` bug
* add official support for v0.21
* `--develop` is no longer required
* add `spack_version` information that can be accessed during configuration, in case two supported versions require different configurations.
* update the documentation to reflect the changes.
> Support Spack v0.21; Deprecate v0.19

- stackinator/builder.py
`set_permissions` was not called for the toplevel directory in `os.walk(directory)`
> add missing set_permissions

- stackinator/repo/packages/cray-gtl/package.py
- stackinator/repo/packages/cray-mpich/package.py
- stackinator/repo/packages/cray-pmi/package.py
For unknown reasons `libmpi_gtl_cuda.so` in cray-gtl@8.1.27 was not linked again `libcuda` and `libcudart`, resulting in linker errors:
- use patchelf to link `libmpi_gtl_cuda.so` to `libcudart`/`libcuda`
- `cray-mpich@8.1.27` depends on `cuda@12`
- update sha256 for mpich 8.1.27 (regenerated tarballs using HPE repo)
- tested `osu_bw -d cuda D D` and `osu_bw H H` on `tasnam`
> mpich 8.1.27 fixes

- docs/recipes.md
- stackinator/schema/environments.json
- stackinator/templates/environments.spack.yaml
Sometimes there's no other way than dealing with deprecated packages. Spack by default does not allow anymore to fetch packages version marked as deprecated, but it still keeps the door open for such edge cases allowing to control the behavior via `config:deprecated`.
This PR exposes this option in `environments.yaml` keeping the default spack behavior (i.e. `false` = don't allow to install deprecated versions).
I didn't had the chance to fully test it, yet. In case this work is in the right direction, I will take care of updating the related documentation too before merging this PR.
> Make spack `config:deprecated` configuration accessible in environment

- stackinator/repo/packages/cray-gtl/package.py
- stackinator/repo/packages/cray-mpich/package.py
- stackinator/repo/packages/cray-pals/package.py
- stackinator/repo/packages/cray-pmi/package.py
- handle `x86` and `arm64` like it is done for cuda package using `platform.machine()`
- set rpath in cray-mpich wrapper for mpich and gtl
- packages in jfrog have been updated with added platform suffix `*.x86_64.tar.gz` and `*.aarch64.tar.gz`.
Tested on clariden for mpich-gcc/nvhpc using osu_bw.
> cray-mpich: add aarch64 versions / set rpaths

- stackinator/repo/packages/cray-mpich/package.py
Remove mpich@8.1.29 from master branch, there was a typo in the conflict and the shasum changed again, because an additional nested directory was required to prevent spack from unpacking `bin`, `lib`, `include` instead of `mpich-nvhpc`.
I've moved the GH enable version to https://github.com/simonpintarelli/stackinator/tree/aarch64
> remove mpich 8.1.29

- stackinator/repo/packages/cray-gtl/package.py
- stackinator/repo/packages/cray-mpich/package.py
- stackinator/repo/packages/cray-pals/package.py
- stackinator/repo/packages/cray-pmi/package.py
manually update packages for cray-mpich 8.1.18 using rpath in mpic++/fort wrappers
> update cray-mpich 8.1.18

- .github/workflows/lint.yaml
- stackinator/repo/packages/aws-ofi-nccl/package.py
- stackinator/repo/packages/cray-mpich/package.py
- stackinator/repo/packages/cuda/package.py
- stackinator/repo/packages/nvhpc/package.py
Enable Grace-Hopper on Santis through:
* adding cray-mpich 8.1.29 for nvidia toolchain
* adding package.py files for `nvhpc` and `cuda` to the stackinator repo
*  to provide the latest cuda 12.3 and nvhpc 24.1 for spack v0.20 a v0.2
* adding an up to date `aws-ofi-nccl` package that enables support for NCCL on Slingshot 11
> Support Grace-Hopper

- stackinator/templates/Makefile.environments
When pinning a specific spack commit inbetween develop and 0.21 in a recipe, the spack version is set to 0.22 and it errors out with a missing parameter passed to `--with-view`.
> Update spack command when using a spack commit between develop and 0.21

- stackinator/repo/packages/cray-mpich/package.py
use `patchelf --add-needed` to link libxpmem.so to mpi libraries.
> link to xpmem

- stackinator/templates/Makefile.environments
Grep for `version=git\.`, for example: `sirius@git.mybranch=develop` is excluded from the build-cache, but not `sirius@=develop`.
Proposal for https://github.com/eth-cscs/stackinator/issues/167
> exclude packages built from a git branch from build cache

- stackinator/etc/add-compiler-links.py
Filter `None` from compiler paths, before calling os.path.dirname.
Compiler paths (for example clang) might be empty.
```
compilers:
- compiler:
spec: clang@=18.1.1
paths:
cc: clang
cxx: clang++
f77: null
fc: null
flags: {}
```
causing the following error:
```
==> Updating view at /user-environment/env/default
...
File "/dev/shm/boeschf/ml-base_env/add-compiler-links.py", line 70, in <module>
local_paths = set([os.path.dirname(v) for k, v in c["paths"].items()])
File "/dev/shm/boeschf/ml-base_env/add-compiler-links.py", line 70, in <listcomp>
local_paths = set([os.path.dirname(v) for k, v in c["paths"].items()])
File "/usr/lib64/python3.6/posixpath.py", line 156, in dirname
p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
...
```
> compiler paths can be null/None

- stackinator/repo/packages/cray-mpich/package.py
For `cray-mpich+cuda` (and `cray-mpich+rocm`), run `patchelf --add-needed libmpi_gtl_cuda.so` (.. `hsa`). 
This is only for convenience, when not using the cray compiler wrapper, `libmpi_gtl_cuda.so` needs to be added manually at the moment. After this change, it's enough to link to `libmpi.so`.
> link `libmpi_gtl_hsa|cuda.so` to cray mpich libraries

- stackinator/recipe.py
I'm not quite sure why the non-cray-mpichs have `cuda_arch=80` hardcoded, but that seems like a leftover from the past so I've at least set `openmpi` to behave like `cray-mpich`, i.e. just use `+cuda` and `cuda_arch` from the environment. Apparently OpenMPI has ROCm support (https://docs.open-mpi.org/en/v5.0.x/tuning-apps/networking/rocm.html) but the `openmpi` spack package does not have ROCm support. I have not attempted to add that support. I guess it's fine if attempting to use `openmpi +rocm` will simply fail to concretize?
Requires https://github.com/eth-cscs/alps-cluster-config/pull/5.
Ping @ajocksch and @boeschf.
> Add support for OpenMPI

- stackinator/templates/Make.user
- stackinator/templates/Makefile
- stackinator/templates/Makefile.compilers
- stackinator/templates/Makefile.environments
- stackinator/templates/Makefile.generate-config
After https://github.com/spack/spack/pull/42334 stackinator started raising some errors due to colorised output.
Just for reference, the error look like this
```bash
env: ‘\033[1m/user-environment/linux-sles15-zen/gcc-7.5.0/squashfs-4.6.1-pl5475bjii2xaf3cafaflr2yidf5754h\033[0m/bin/mksquashfs’: No such file or directory
```
In other places `spack --color=never` is already used, so I just applied the same solution also in the other parts that were triggering the error. 
This applies for sure to `develop` branch, but in principle it should not harm in general.
Actually, I think it might be a good idea to have a different `$(SPACK)` variable that already embeds the `--color=never`, so it can be safely used where we use spack not as build tool but as helper to retrieve information (e.g. get …
> Add a couple of missing spack --color=never

- stackinator/recipe.py
- stackinator/templates/Makefile
- stackinator/templates/Makefile.compilers
- stackinator/templates/Makefile.environments
As pointed out by @albestro.
from spack changelog (https://github.com/spack/spack/blob/develop/CHANGELOG.md#L313)
```
buildcache push: make `--allow-root` the default and deprecate the option (#38878)
```
It was announced to remove `--allow-root` in spack v0.22, although it is still there with the warning:
```
if args.allow_root:
tty.warn(
"The flag `--allow-root` is the default in Spack 0.21, will be removed in Spack 0.22"
)
```
> buildcache create `--allow-root` is default in current spack versions

- stackinator/main.py
`http_proxy` seems to be default and mandatory on todi/eiger. Print  http_proxy  in the `env --ignore-environment` command. 
It shouldnt' affect balfrin etc, setting `https_proxy=""` seems to have no effect.
> print http_proxy in env command

- stackinator/main.py
My bad again, after reformatting the whitespace between "PATH" and "/spack" were lost.
> Http proxy missing whitespace

- stackinator/templates/environments.spack.yaml
Environments with only a single compiler defined generated spack.yaml contained:
```
packages:
require:
- one_of : []
```
Which caused concretization errors.
This PR only adds `pakcages.require.one_of` if `toolchain_constraints` is not empty.
> do not specify one_of if toolchain_constraints is empty

- stackinator/builder.py
- stackinator/templates/Makefile
Running `make cache-force` previously pushed `nvhpc` and `cuda` and also `@git.<id>` packages to the build cache.
> exclude develop (git branch), cuda and nvhpc from cache-force

- stackinator/builder.py
- stackinator/templates/Make.user
Current `spack@develop` wants to read config from `SPACK_USER_CONFIG_PATH ` despite it has been set to `/dev/null`. Use $HOME hidden by tmpfs instead.
```
[daint][simonpi@nid006880 build-bwrap]$ env --ignore-environment http_proxy="$http_proxy" https_proxy="$https_proxy" no_proxy="$no_proxy" PATH=/usr/bin:/bin:`pwd`/spack/bin HOME=$HOME make store.squashfs -j32
/dev/shm/simonpi/build-bwrap/bwrap-mutable-root.sh --tmpfs ~ --bind /dev/shm/simonpi/build-bwrap/tmp /tmp --bind /dev/shm/simonpi/build-bwrap/store /user-environment spack --version > spack-version
spack arch... ==> Error: Path is not a file or is not readable: /dev/null/config.yaml: [Errno 20] Not a directory: '/dev/null/config.yaml'
spack version... 0.23.0.dev0 (0fee2c234ef1eda5483a2da5c6bd679c48d7ab26)
checking if spack …
```
> Avoid /dev/null for spack@develop

- stackinator/builder.py
Reverts #199, and instead explicitly decodes the result of `git rev-parse` to ensure the commit is printed in the Makefile without a `b'...'` prefix.
> Fix printing of spack commit into generated Makefile

- stackinator/templates/Makefile
Should we run `chmod -R a+rX $(STORE)` before creating the squashfs file?
Currently chmod needs to be run manually in `post-install`. User wouldn't need to think about this when writing `post-install` hooks.
Ping @lukasgd.
> run chmod -R a+rX $(STORE) before creating sqfs

- .github/workflows/main.yaml
- stackinator/builder.py
- stackinator/recipe.py
Clean up build cache exclusion list.
Add perl to the list, because pulling perl from build cache breaks builds of many PerlPackages
* do not push perl to build cache
* consistent build cache exclusion list
> more consistent build cache exclusion

- pyproject.toml
- stackinator/recipe.py
- stackinator/templates/Makefile.compilers
- stackinator/templates/compilers.gcc.spack.yaml
Changelog:
- remove hard-coded variants (not used, templates ones are)
- remove duplicated target from `Makefile.compilers` (70f1ebb8220f62cd6521398e357a95bddd2adeba)
- added `ruff` to `pyproject.toml`
- some formatting and typos fixing
About first point, I currently went for enabling `gcc +profiled` in the template as it was in the unused hard-coded variants, just because it sounds like a good thing. I'm not sure how much difference it will make, but it can make a difference in terms of cache reuse for future uenv builds. Indeed, AFAICT, `spack info gcc` reports
```
Variants:
...
bootstrap [true]                   false, true
Enable 3-stage bootstrap
...
when %gcc+bootstrap
profiled [false]                 false, true
Use Profile Guided Optimization
```
which means that before this PR …
> Some minor fixes and cleanups

- docs/recipes.md
Opening this PR for adding an hint about package backporting that might be beneficial for some users.
I think this PR is relevant
- for sure for `release/v5` which supports spack up to 0.23, where packages will not get updates anymore
- but it might useful also more generally also for spack 1.0 and newer (so `main`), since one might want to use a specific commit for spack but have a more recent version of a package that has been updated after that commit.
As always, open for any comment and thanks in advance.
> docs: hint about backporting a package

- stackinator/builder.py
- stackinator/etc/envvars.py
Also fixes unprotected access to `extra_attributes` when dealing with compilers (fixed by @biddisco in #243).
> Fix repo paths to ensure builtin and alps repos don't overwrite each other

- stackinator/recipe.py
In the cluster configuration the file `packages.yaml` is optional
https://github.com/eth-cscs/stackinator/blob/5581430ce63f5ecfd5dae8e59b578e145b7767cf/stackinator/recipe.py#L91-L98
but at the same time there is an implicit requirement since if there is no `gcc` specified in `packages.yaml`, we should raise an exception.
https://github.com/eth-cscs/stackinator/blob/5581430ce63f5ecfd5dae8e59b578e145b7767cf/stackinator/recipe.py#L100-L106
With this small PR, the `RuntimeError` with a nicer and a bit more informative error message will be raised also in case no `packages.yaml` or it is available but no `gcc` is specified.
note: I faced this many times when by mistake I ended up passing the wrong path for the cluster configuration, and the path didn't contain the "usual" yaml files.
> minor: improve error management for missing system gcc compiler in system configuration

- stackinator/main.py
To fix the following error, observed in some CI jobs:
https://gitlab.com/cscs-ci/ci-testing/webhook-ci/mirrors/551234120955960/1440398897047560/-/jobs/11217520542#L72
> improve robustness of log file naming in notty sessions

- stackinator/etc/Make.inc
It is a very small and marginal change, but it might be helpful/interesting in certain situations knowing how much a concretization step took.
Just as an example, this is how it looks like.
```
/usr/bin/time -f "\"%C\" took %e seconds." spack -e uenv_tools/ concretize -f
==> Concretized 1 spec:
-   ndag2eb  squashfs@4.6.1+gzip~lz4~lzo~static~xz~zstd build_system=makefile default_compression=gzip platform=linux os=sles15 target=neoverse_v2 %c=gcc@14.2.0
[+]  hcns3gf      ^compiler-wrapper@1.0 build_system=generic platform=linux os=sles15 target=neoverse_v2
[e]  f6ia2r5      ^gcc@14.2.0~binutils+bootstrap~graphite~mold~nvptx~piclibs~profiled~strip build_system=autotools build_type=RelWithDebInfo languages:='c,c++,fortran' platform=linux os=sles15 target=aarch64
-   c3kepa7 …
```
> Measure time of all concretization steps
