eth-cscs/stackinator

- etc/Makefile
- lib/sstool/main.py
- templates/Makefile.generate-config
> remove modules.yaml from the installed image

- lib/sstool/main.py
> print logfile name on error

- lib/sstool/main.py
- templates/Makefile
- templates/Makefile.generate-config
> Add support for mpich/mvapich2, fix squashfs timestaps

- sstool/main.py
> Set 4.1rc3 the default version for MPICH

- sstool/__init__.py
- sstool/main.py
> Replace string formatting with f-strings

- readme.md
- sstool/main.py
- templates/Makefile
> build modules automatically if configured

- bin/sstool
- sstool/main.py
> Use pathlib for file/path operations

- sstool/main.py
> Make mpich@4.1 the default mpich

- bin/sstool
> remove hard-coded python from sstool

- stackinator/__init__.py
- stackinator/builder.py
- stackinator/main.py
- stackinator/recipe.py
> Split functionality in multiple modules

- stackinator/main.py
- stackinator/recipe.py
Added --system flag to stack-config that overrides the default system in a recipe config.yaml.
Also reduced verbosity of error messages.
Fixes #65
> add --system flag to override system in config.yaml

- stackinator/cluster-config/balfrin/packages.yaml
- stackinator/cluster-config/clariden/packages.yaml
- stackinator/cluster-config/hohgant/packages.yaml
Update `cluster-config/*/package.yaml` files to point to the new location of xpmem.
> update external xpmem version

- stackinator/repo/packages/cray-mpich/package.py
https://github.com/eth-cscs/stackinator/issues/103
> cpe 23.03, mpich 8.1.25

- stackinator/etc/add-compiler-links.py
> add missing newlines each line of the env activation scripts

- docs/recipes.md
- stackinator/builder.py
- stackinator/recipe.py
- stackinator/templates/Makefile
- unittests/recipes/host-recipe/config.yaml
- unittests/recipes/host-recipe/post-install
- unittests/recipes/host-recipe/post-install.sh
Add support for running a post install script if it is provided in a recipe.
> post install hook

- stackinator/recipe.py
... not as PosixPath, so that they serialise
> store env root paths as strings

- docs/build-caches.md
- docs/development.md
- stackinator/recipe.py
- stackinator/templates/Makefile
> Add makefile target for pushing all packages to build cache

- docs/recipes.md
- stackinator/builder.py
- stackinator/recipe.py
- stackinator/templates/Makefile
- unittests/recipes/host-recipe/pre-install
Add pre-install hook, similar to post-install hook feature
> Add pre-install hook

- stackinator/builder.py
- replace `shutil.copytree` and `shutil.copy2` by a custom `install` command
- do not touch `shutil.copy` (it's not used to write to `store/` directory)
`shutil.copytree` can take a custom copy_function, unfortunately this isn't enough, since it is only called for the files. Therefore it doesn't allow to control the permissions of the directory.
> replace shutil.copytree and shutil.copy2 by custom install command

- stackinator/templates/Makefile
update Makefile to run post-isntall after env meta has been generated
> run post-install after uenv meta data has been generated

- stackinator/templates/Makefile
Sorry, I accidentally used spaces instead of tab (#206) in the makefile...
> whitespace mistake in makefile

- docs/recipes.md
Same as #217 applied also on main branch.
> docs: hint about backporting a package (for main branch)

- docs/installing.md
- docs/recipes.md
> Add spack-packages config fields to documentation
